### ISSUE TITLE
Incorrect decode / Targon set3

### ISSUE THREAD

**Issue by MaouLegna** [pholzmgit/lordecks#1]
When decoding a decklist with Targon's cards from set3 it returns cards with a 5digit card number

Example deck_code:
CMBAEAYJ3EA5WAIHAQDQCDJGJFGF23ICAIBQTVYB3QAQIBAHDQSTW2QBAECAOWI

lordecks::get_decklist_from_code("CMBAEAYJ3EA5WAIHAQDQCDJGJFGF23ICAIBQTVYB3QAQIBAHDQSTW2QBAECAOWI")

the set3-MT cards have cardCode:
03MT11393
03MT11649
03MT11137
03MT11777

while the expected code should be:
03MT217
03MT219
03MT215
03MT220

(returned with **lor_deckcodes$decode$decode_deck** )

**Comment by MaouLegna** [comment]
I didn't even read the README with the sufficient amount of attention. The Issue doesn't exist at all

**Comment by pholzmgit** [comment]
Sorry for the late response, I was on vacation.  The issue you ran into was in fact unintended, and I've now adapted this so you get the correct results:

```
code <- "CMBAEAYJ3EA5WAIHAQDQCDJGJFGF23ICAIBQTVYB3QAQIBAHDQSTW2QBAECAOWI"

lordecks::get_decklist_from_code(code)
```

```
   cardcode count faction set card_number
1   03MT217     3      MT   3         217
2   03MT219     3      MT   3         219
3   04SH001     3      SH   4         001
4   04SH013     3      SH   4         013
5   04SH038     3      SH   4         038
6   04SH073     3      SH   4         073
7   04SH076     3      SH   4         076
8   04SH093     3      SH   4         093
9   04SH109     3      SH   4         109
10  03MT215     2      MT   3         215
11  03MT220     2      MT   3         220
12  04SH028     2      SH   4         028
13  04SH037     2      SH   4         037
14  04SH059     2      SH   4         059
15  04SH106     2      SH   4         106
16  04SH089     1      SH   4         089
```
