### ISSUE TITLE
Incorrect decode Targon set 3

### ISSUE THREAD

**Issue by Alessandro-Balconi** [pholzmgit/lordecks#2]
Opening this since the previous issue was closed by its author, but I think this needs to be addressed.
Currently, the tracker returns cards with a 5 digits card number when decoding targon set 3 cards (I think this is specific to the Aphelios champion expansion cards, not all of set 3 Targon cards, but not 100% sure).

Here is an example:

code <- "CMBAEAYJ3EA5WAIHAQDQCDJGJFGF23ICAIBQTVYB3QAQIBAHDQSTW2QBAECAOWI"

R decoder:

lordecks::get_decklist_from_code(code)

     cardcode count faction set card_number
 1  03MT11393     3      MT   3       11393
 2  03MT11649     3      MT   3       11649
 3    04SH001     3      SH   4         001
 4    04SH013     3      SH   4         013

While the Python implementation correctly returns 3 digits card numbers for those cards:

 Python decoder:

reticulate::py_install("lor_deckcodes", pip = TRUE)
lor_deckcodes <- reticulate::import("lor_deckcodes")
lor_deckcodes$decode$decode_deck(code)

 "3:03MT217" "3:03MT219" "3:04SH001" "3:04SH013"

**Comment by pholzmgit** [comment]
Thanks for the example. 

The byte order for card numbers >127 was handled differently compared to other implementations. Outside of that expansion that was never the case, which is why it didn't showed up in the tests. I've adapted this in 7d8b8bc037c25ec8571dfd7b3690285f88e698fa and it now produces the expected results:

```
code <- "CMBAEAYJ3EA5WAIHAQDQCDJGJFGF23ICAIBQTVYB3QAQIBAHDQSTW2QBAECAOWI"

R decoder:

lordecks::get_decklist_from_code(code)
```

```
   cardcode count faction set card_number
1   03MT217     3      MT   3         217
2   03MT219     3      MT   3         219
3   04SH001     3      SH   4         001
4   04SH013     3      SH   4         013
5   04SH038     3      SH   4         038
6   04SH073     3      SH   4         073
7   04SH076     3      SH   4         076
8   04SH093     3      SH   4         093
9   04SH109     3      SH   4         109
10  03MT215     2      MT   3         215
11  03MT220     2      MT   3         220
12  04SH028     2      SH   4         028
13  04SH037     2      SH   4         037
14  04SH059     2      SH   4         059
15  04SH106     2      SH   4         106
16  04SH089     1      SH   4         089
```
